spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: PassWord
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create
